# Generated by Django 4.1.1 on 2022-09-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_account_name_alter_account_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="id",
            new_name="code",
        ),
    ]
